Feature/loading message
MarissaLZ/pet-adoption pull request #27
Opened 2022-08-24 14:27 UTC by Jay-zar

This adds a basic loading message while the API call is fetching data. Loading state is handled as a context on the Adopt page with state set in ZipCodeInput.

2022-08-24 16:24 UTC, tarikutk requested changes
is it for a reason that you deleted all the lines in .env.example ? or may be it was just because the branch was not created from the lates main branch. also in adopt page you replaced < Search/> with < ZipCodeInput/>. so you may want to revert that because the < Search/> has the <Zipcodeinput/> and also buttons that will helps us filter

2022-08-24 18:03 UTC, MarissaLZ commented on src/components/ZipCodeInput.js
> +
These lines can be deleted. I removed them when I created the <SearchContext/> which takes care of the zipcode value now.

2022-08-24 18:07 UTC, MarissaLZ commented on src/pages/Adopt.js
> -      <PetList />
These two lines are needed to have the <Search/> component that allows the user to select a zip code and pet type. <ZipCodeInput/> was moved to Search.js in a previous pull.

2022-08-24 18:10 UTC, MarissaLZ commented on src/pages/Adopt.js
> +import ZipCodeInput from "../components/ZipCodeInput"
This line can be removed since `<ZipCodeInput/>` was moved to Search.js

2022-08-24 20:16 UTC, MarcusCHill approved these changes
Loading works well, no errors.  To address warning message Adopt.js imports useState so the React. can be ommited on line 10 or the import can be omitted.

2022-08-24 23:33 UTC, tarikutk approved these changes

2022-08-25 01:13 UTC, MarissaLZ approved these changes

2022-08-25 14:59 UTC, merged