Add context wrapper
MarissaLZ/pet-adoption pull request #37
Opened 2022-09-01 23:06 UTC by MarissaLZ

### In This PR

- Refactors context file to return a `<FurrdoptionProvider/>` component which wraps all children with a  `<FurrdoptionContext.Provider>` component

- Refactors context file to prepare context for testing

2022-09-02 22:28 UTC, mnca16 approved these changes

2022-09-03 05:20 UTC, tarikutk requested changes
- Good work. we just need to make some adjustment. adopt page is failing because this lines were removed. `const { petList } = useContext(PetsContext)`<PetList` animalList={petList} />`
- Favorites page is failing because the context is not updated to use the furrdoptionContext.

2022-09-03 05:21 UTC, tarikutk commented
also lets not forget to run the app whenever we make some changes to make sure everything is working as expected.

2022-09-03 05:31 UTC, MarissaLZ commented
Fixed it! I thought I had resolved all the conflicts correctly but it looks like I missed those pages.

2022-09-03 05:36 UTC, tarikutk approved these changes

2022-09-03 05:41 UTC, merged